/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppleHealthRouteImport } from './routes/apple-health'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RootsRouteImport } from './routes/roots'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminLabRouteImport } from './routes/admin/lab'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminRootsRouteImport } from './routes/admin/roots'
import { Route as RootsIdRouteImport } from './routes/roots.$id'
import { Route as OauthOuraReturnRouteImport } from './routes/oauth.oura.return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleHealthRoute = AppleHealthRouteImport.update({
  id: '/apple-health',
  path: '/apple-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsRoute = RootsRouteImport.update({
  id: '/roots',
  path: '/roots',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLabRoute = AdminLabRouteImport.update({
  id: '/admin/lab',
  path: '/admin/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRootsRoute = AdminRootsRouteImport.update({
  id: '/admin/roots',
  path: '/admin/roots',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsIdRoute = RootsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RootsRoute,
} as any)
const OauthOuraReturnRoute = OauthOuraReturnRouteImport.update({
  id: '/oauth/oura/return',
  path: '/oauth/oura/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apple-health': typeof AppleHealthRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/cycle': typeof CycleRoute
  '/devices': typeof DevicesRoute
  '/invite': typeof InviteRoute
  '/journal': typeof JournalRoute
  '/medications': typeof MedicationsRoute
  '/privacy': typeof PrivacyRoute
  '/roots': typeof RootsRouteWithChildren
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/roots': typeof AdminRootsRoute
  '/roots/$id': typeof RootsIdRoute
  '/oauth/oura/return': typeof OauthOuraReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apple-health': typeof AppleHealthRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/cycle': typeof CycleRoute
  '/devices': typeof DevicesRoute
  '/invite': typeof InviteRoute
  '/journal': typeof JournalRoute
  '/medications': typeof MedicationsRoute
  '/privacy': typeof PrivacyRoute
  '/roots': typeof RootsRouteWithChildren
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/roots': typeof AdminRootsRoute
  '/roots/$id': typeof RootsIdRoute
  '/oauth/oura/return': typeof OauthOuraReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apple-health': typeof AppleHealthRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/cycle': typeof CycleRoute
  '/devices': typeof DevicesRoute
  '/invite': typeof InviteRoute
  '/journal': typeof JournalRoute
  '/medications': typeof MedicationsRoute
  '/privacy': typeof PrivacyRoute
  '/roots': typeof RootsRouteWithChildren
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/roots': typeof AdminRootsRoute
  '/roots/$id': typeof RootsIdRoute
  '/oauth/oura/return': typeof OauthOuraReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apple-health'
    | '/astrology'
    | '/auth'
    | '/cycle'
    | '/devices'
    | '/invite'
    | '/journal'
    | '/medications'
    | '/privacy'
    | '/roots'
    | '/terms'
    | '/trends'
    | '/welcome'
    | '/admin/lab'
    | '/admin/members'
    | '/admin/roots'
    | '/roots/$id'
    | '/oauth/oura/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apple-health'
    | '/astrology'
    | '/auth'
    | '/cycle'
    | '/devices'
    | '/invite'
    | '/journal'
    | '/medications'
    | '/privacy'
    | '/roots'
    | '/terms'
    | '/trends'
    | '/welcome'
    | '/admin/lab'
    | '/admin/members'
    | '/admin/roots'
    | '/roots/$id'
    | '/oauth/oura/return'
  id:
    | '__root__'
    | '/'
    | '/apple-health'
    | '/astrology'
    | '/auth'
    | '/cycle'
    | '/devices'
    | '/invite'
    | '/journal'
    | '/medications'
    | '/privacy'
    | '/roots'
    | '/terms'
    | '/trends'
    | '/welcome'
    | '/admin/lab'
    | '/admin/members'
    | '/admin/roots'
    | '/roots/$id'
    | '/oauth/oura/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppleHealthRoute: typeof AppleHealthRoute
  AstrologyRoute: typeof AstrologyRoute
  AuthRoute: typeof AuthRoute
  CycleRoute: typeof CycleRoute
  DevicesRoute: typeof DevicesRoute
  InviteRoute: typeof InviteRoute
  JournalRoute: typeof JournalRoute
  MedicationsRoute: typeof MedicationsRoute
  PrivacyRoute: typeof PrivacyRoute
  RootsRoute: typeof RootsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TrendsRoute: typeof TrendsRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminLabRoute: typeof AdminLabRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRootsRoute: typeof AdminRootsRoute
  OauthOuraReturnRoute: typeof OauthOuraReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple-health': {
      id: '/apple-health'
      path: '/apple-health'
      fullPath: '/apple-health'
      preLoaderRoute: typeof AppleHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots': {
      id: '/roots'
      path: '/roots'
      fullPath: '/roots'
      preLoaderRoute: typeof RootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lab': {
      id: '/admin/lab'
      path: '/admin/lab'
      fullPath: '/admin/lab'
      preLoaderRoute: typeof AdminLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roots': {
      id: '/admin/roots'
      path: '/admin/roots'
      fullPath: '/admin/roots'
      preLoaderRoute: typeof AdminRootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/$id': {
      id: '/roots/$id'
      path: '/$id'
      fullPath: '/roots/$id'
      preLoaderRoute: typeof RootsIdRouteImport
      parentRoute: typeof RootsRoute
    }
    '/oauth/oura/return': {
      id: '/oauth/oura/return'
      path: '/oauth/oura/return'
      fullPath: '/oauth/oura/return'
      preLoaderRoute: typeof OauthOuraReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RootsRouteChildren {
  RootsIdRoute: typeof RootsIdRoute
}

const RootsRouteChildren: RootsRouteChildren = {
  RootsIdRoute: RootsIdRoute,
}

const RootsRouteWithChildren = RootsRoute._addFileChildren(RootsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppleHealthRoute: AppleHealthRoute,
  AstrologyRoute: AstrologyRoute,
  AuthRoute: AuthRoute,
  CycleRoute: CycleRoute,
  DevicesRoute: DevicesRoute,
  InviteRoute: InviteRoute,
  JournalRoute: JournalRoute,
  MedicationsRoute: MedicationsRoute,
  PrivacyRoute: PrivacyRoute,
  RootsRoute: RootsRouteWithChildren,
  TermsRoute: TermsRoute,
  TrendsRoute: TrendsRoute,
  WelcomeRoute: WelcomeRoute,
  AdminLabRoute: AdminLabRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRootsRoute: AdminRootsRoute,
  OauthOuraReturnRoute: OauthOuraReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
